# Generated by Django 4.0 on 2022-01-02 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_testapi_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testapi',
            name='id',
        ),
        migrations.AlterField(
            model_name='testapi',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
