# Generated by Django 4.0 on 2022-01-02 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_remove_testapi_id_alter_testapi_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testapi',
            name='uuid',
        ),
        migrations.AddField(
            model_name='testapi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
