# Generated by Django 4.0 on 2022-01-02 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_remove_testapi_uuid_testapi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
